### ISSUE TITLE
[ISSUE] Cluster connected to instance pool causes apply failure after refresh

### ISSUE THREAD

**Issue by sdebruyn** [databrickslabs/terraform-provider-databricks#212]
Exactly the same issue as #157, except now it's complaining about a different field:

```
databricks_cluster.cluster: Modifying... [id=0805-211114-arcs340]

Error: The field 'enable_elastic_disk' cannot be supplied when an instance pool ID is provided.
Please consult API docs at https://docs.databricks.com/dev-tools/api/latest/clusters.html#edit for details.

  on cluster.tf line 11, in resource "databricks_cluster" "cluster":
  11: resource "databricks_cluster" "cluster" {
```

**Comment by nfx** [comment]
@stikkireddy reflect_resource should fix this issue

**Comment by stikkireddy** [comment]
The old instance pool issues are still there, so reflect_resource fixes enable_elastic_disk but does not resolve instance_profile_id.

**Comment by stikkireddy** [comment]
@nfx so the way we set values dont work appropriately for the way the struct is laid out for clusterinfo aws attributes.

The scenario is a AWS user who creates a instance pool + cluster:

1.

```hcl
resource "databricks_instance_pool" "some-pool" {
// pool data
}

resource "databricks_cluster" "some-cluster" {
// cluster data but aws_attributes is not defined so aws_attrbutes {} does not exist
}
```

2. Everything works just dandy and `aws_attrbutes` is nil so it is skipped in setting state. Unfortunately if someone goes in the UI and changes the instance profile arn to another value (this is a value captured in aws_attributes) we do not ever set this value in the state as aws_attributes is skipped because it is nil ptr. 

What we should be doing in this scenario is identify the schema drifted and update the cluster to set the arn back to 0.

There are a few options:
1. We add a tag on model.ClusterInfo to skip the reflection based set and we can later have a separate golang function to set the value after some logic that we had before. This is a one off thing.
```go
type ClusterInfo struct { 
        ...
	AwsAttributes          *AwsAttributes     `json:"aws_attributes,omitempty" tf:"skip_set"`
	...
}
```
2. The alternative is that the user would need to move the instance_profile_id to the base schema but unfortunately that breaks the reflection mapper as it builds it based off of the struct. 

3. The user is required to put to enforce but it may have some issues as we skip empty strings:
```hcl
resource "databricks_instance_pool" "some-pool" {
// pool data
}

resource "databricks_cluster" "some-cluster" {
  aws_attributes {
      instance_profile_arn = ""
  }
}
```

Any other suggestions would be much appreciated.

**Comment by nfx** [comment]
@stikkireddy look into ResourceData - i think you'll be able to compare the state and most likely not need `skip_set`

**Comment by stikkireddy** [comment]
@sdebruyn there is a pr #231 that should help resolve this

**Comment by stikkireddy** [comment]
@sdebruyn the pr 231 is merged in please reopen if the issue is not resolved
